baseurl = "/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Emily Martinez"
theme = "hugo-theme-dream"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# copyright = ""

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

[params]
  author = "Emily"
  motto = "R enthusiast and art plebe"
  # description = ""
  # avatar = ""
  
  # email = ""
   github = "https://github.com/em1729"
  # linkedin = ""
  # codepen = ""
  # stackoverflow = ""

  siteStartYear = 2019
  aboutHeader = "About"

  paginate = 4

  # favicon = "/favicon.ico"

  # lightMode = true
