baseurl = "/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Emily Martinez"
theme = "hugo-theme-dream"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true

# copyright = ""

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

[params]
  author = "Emily"
  motto = "risueña"
  description = "R enthusiast and art plebe"
  avatar = "/img/fall7.png"
  
  # email = "emartinez207@gmail.com"
   github = "https://github.com/em1729"
  # linkedin = "https://www.linkedin.com/in/emartinez3097/"
  # codepen = ""
  # stackoverflow = ""

  siteStartYear = 2019
  aboutHeader = "About"

  paginate = 4

  # favicon = "/favicon.ico"

  # lightMode = true
